import os
from pickle import TRUE
from yacs.config import CfgNode as CN

_C = CN()

_C.DEVICE = "mps"
_C.OUTPUT_DIR = "./output"
_C.SEED = -1


# MODEL
_C.MODEL = CN()
_C.MODEL.BACKBONE = ""
_C.MODEL.NECK = ""
_C.MODEL.HEAD = "BASELINE_2DTO3D"
_C.MODEL.ONLY_HEAD = True

_C.MODEL.WEIGHT = ""
_C.MODEL.DROPOUT_P = 0.5

_C.MODEL.BASELINE_2DTO3D = CN()
_C.MODEL.BASELINE_2DTO3D.CHANNELS = (1024, 1024, 1024,)


# INPUT
_C.INPUT = CN()
_C.INPUT.MAX_SIZE_TRAIN = 1010
_C.INPUT.MIN_SIZE_TRAIN = 1000
_C.INPUT.MAX_SIZE_TEST = 1010
_C.INPUT.MIN_SIZE_TEST = 1000

_C.INPUT.N_JOINTS = 16
_C.INPUT.RANDOM_FLIP = False
_C.INPUT.FORMAT = "BGR"


# DATASETS
_C.DATASETS = CN()
_C.DATASETS.TRAIN = ()
_C.DATASETS.TEST = ()
_C.DATASETS.N_VIEWS = 1
_C.DATASETS.TEMPORAL = False


# DATALOADER
_C.DATALOADER = CN()
_C.DATALOADER.NUM_WORKERS = 4
_C.SHUFFLE = False


# SOLVER
_C.SOLVER = CN()
_C.SOLVER.MAX_EPOCH = 200
_C.SOLVER.STEPS = ()
_C.SOLVER.BASE_LR = 0.001

_C.SOLVER.MOMENTUM = 0.9
_C.SOLVER.WEIGHT_DECAY = 0.0005
# _C.SOLVER.WEIGHT_DECAY_BIAS = 0
_C.SOLVER.GAMMA = 0.1

_C.SOLVER.CHECKPOINT_PERIOD = 2500
_C.SOLVER.TEST_PERIOD = 0

_C.SOLVER.IMS_PER_BATCH = 64

