MODEL:
  HEAD: "simple3d_baseline"
  WEIGHT: ""
  BASELINE_2DTO3D:
    CHANNELS: (1024, 1024, 1024)
  
DATASETS:
  TRAIN: ("Human36m",)
  TEST: ("Human36m",)

SOLVER:
  BASE_LR: 0.004
  WEIGHT_DECAY: 0.0001
  STEPS: (100, 150, 180)
  MAX_EPOCH: 200
  GAMMA: 0.96
  IMS_PER_BATCH: 256
  CHECKPOINT_PERIOD: 20
  TEST_PERIOD: 10
